config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/new', to: 'articles#new'
  get '/signup', to: 'users#new'
  
  resources :articles
  resources :users, except: [:new]
  
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories
	validates :title, presence: true, length: {minimum: 3, maximum: 50}
	validates :description, presence: true, length: {minimum: 10, maximum: 10000}
	validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    before_save {self.email = email.downcase}
    validates :username, presence: true, uniqueness: {case_sensitive: false},
                length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false},
                length: {maximum: 105}, format: {with: VALID_EMAIL_REGEX}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if not logged_in? then
      flash[:danger] = "You most be loged in to preform that acction"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController	
	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	
	def index
		@articles = Article.all
	end
	
	def new
		@article = Article.new
	end
	
	def edit
	end
	
	def create
		@article = Article.new(article_params)
		@article.user = current_user
		
		if @article.save then
			flash[:success] = "Article was successfully created"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end
	
	def show
	end
	
	def destroy
		@article.destroy
		flash[:success] = "Article was successfully deleted"
		redirect_to articles_path
	end
	
	def update
		@article = Article.find(params[:id])
		if @article.update(article_params) then
			flash[:success] = "Article was successfully updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end
	
	private
		def set_article
			@article = Article.find(params[:id])
		end
		
		def article_params
			params.require(:article).permit(:title, :description)
		end
		
		def require_same_user
			if current_user != @article.user and not current_user.admin? then
				flash[:danger] = "You can only edit or delete your own articles"
				redirect_to root_path
			end
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    
    def index
        @categories = Category.all
    end
    
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save then
            flash[:succes] = "Category was successfully created"
            redirect_to categories_path
        else
            render 'new' 
        end
    end
    
    def show
        
    end
    
    private
    def category_params
        params.require(:category).permit(:name)
    end
    
    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)then
            flash[:danger] = "Only admins can preform that acction"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        redirect_to articles_path if logged_in?
    end
    
    def about
    
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user and user.authenticate(params[:session][:password]) then
            session[:user_id] = user.id
            flash[:success] = "Loged in as #{user.username}"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Error"
            render 'new'            
        end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:notice] = "Loged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show, :destroy]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]
	
    def index
		@users = User.all
	end
    
    def new
       @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save then
            session[:user_id] = @user.id
           flash[:success] = "Welcome to Alphe Blog #{@user.username}!"
           redirect_to user_path(@user)
        else
           render 'new' 
        end
    end
    
    def edit
    end
    
    def update
        if @user.update(user_params) then
            flash[:success] = "Yout account was successfully updated"
            redirect_to articles_path
        else
           render 'edit' 
        end
    end
    
    def show
    end
    
    def destroy
        @user.destroy
        flash[:danger] = "User and all theirs articles have been destroyed"
        redirect_to users_path
    end
    
    private
    def user_params
       params.require(:user).permit(:username, :email, :password)
    end
    
    def set_user
        @user = User.find(params[:id])
    end
    
    def require_same_user
       if current_user != @user and not current_user.admin? then
            flash[:danger] = "You can only edit your own account"
			redirect_to root_path
        end
    end
    
    def require_admin
        if logged_in? and not current_user.admin? then
            flash[:danger] = "Only admins can preform that acction"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/views/articles/_article.html.erb
<%= link_to "Create new article", new_article_path, class: "btn btn-xs btn-primary" %>
<br>
<br>

<script>
$(document).ready(function() {
  $("#search").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#table tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

<input class="form-control" id="search" type="text" placeholder="Search..">
  
<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Created by</th>
            <th>Created</th>
            <th>Updated</th>
        </tr>
    </thead>
    <tbody id="table">
    <% obj.each do |article| %>
        <tr>
            <td><%= article.title %></td>
            <td><%= truncate(article.description, length: 50) %></td>
            <td><%= if article.user then article.user.username else "Unknown" end %>
            <% if logged_in? and (current_user == article.user or current_user.admin?) then %>
                <td><%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %></td>
                <td><%= link_to "Delete", article_path(article), method: :delete, 
                    data: {confirm: "Are you sure you want to delete this article?"}, 
                    class: "btn btn-xs btn-danger" %></td>
            <% else %>
                <td><button class="btn btn-xs btn-primary" disabled>Edit</button></td>
                <td><button class="btn btn-xs btn-danger" disabled>Delete</button></td>
            <% end %>
            <td><%= link_to "View", article_path(article), class: "btn btn-xs btn-success" %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <h2>The following errors prevented the article from getting created</h2>
    
    <div class="alert alert-danger" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <p><%= @article.errors.full_messages.length %> errors prohibited this article from being saved</p>
        <% @article.errors.full_messages.each do |msg| %>
            <p>&emsp;
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <%= msg %>
            </p>
        <% end %>
    </div>
<% end %>

<div class="row">
    <div class="col-xs-12">
      <%= form_for(@article, :html => {role: "form"}) do |f| %>
          <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :title %> 
                </div>
                <div class="col-sm-10">
                    <%= f.text_field :title, class: "input form-control", placeholder: "Title", autofocus: true %>   
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :description %>
                </div>
                <div class="col-sm-10">
                    <%= f.text_area :description, rows: 10, class: "text-box form-control", placeholder: "Article body", autofocus: true %>
                <div class="form-group">
                    <hr>
                    <div class="col-sm-0">
                        <%= f.submit class: "btn btn-primary"%>
                        <%= link_to "Back to articles listing", articles_path, style: 'float: right' %>
                    </div>
                </div>
            </div>
        <% end %>  
    </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>

<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<% if @article.errors.any? %>
<h2>The following errors prevented the article from getting created</h2>

    <% @article.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger" role="alert">
            <p>
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            <%= msg %>
            </p>
        </div>
    <% end %>
<% end %>

<h1 align="center"><%= @article.title %></h1>

<div class="well col-xs-8 col-xs-offset-2">
    <h4 class="center"><string><%= @article.title %></string></h4>
    <hr>
    <%= simple_format(@article.description) %>
    
    <div class="article-actions">
       <% if logged_in? and (current_user == @article.user or current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete", article_path(@article), method: :delete, 
            data: {confirm: "Are you sure you want to delete this article?"}, 
            class: "btn btn-xs btn-danger" %>
        <% else %>
            <td><button class="btn btn-xs btn-primary" disabled>Edit</button></td>
            <td><button class="btn btn-xs btn-danger" disabled>Delete</button></td>
        <% end %>
        <%= link_to "All articles", articles_path, class: "btn btn-xs btn-success" %>
    </div>
</div>

<hr>
    <p>Created: <%= time_ago_in_words(@article.created_at) %> ago</p>
    <p>Last updated: <%= time_ago_in_words(@article.updated_at) %> ago</p>
<hr>

<div class="container col-xs-12">
    <%= link_to "Back to articles listing", articles_path %>
</div>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>
    <tbody id="table">
    <% @categories.each do |category| %>
        <tr>
            <td><strong><%= link_to "#{category.name}", category_path(category) %></strong></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<% if @category.errors.any? %>
    <h2>The following errors prevented the category from getting created</h2>
    
    <div class="alert alert-danger" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <p><%= @category.errors.full_messages.length %> errors prohibited this category from being saved</p>
        <% @category.errors.full_messages.each do |msg| %>
            <p>&emsp;
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <%= msg %>
            </p>
        <% end %>
    </div>
<% end %>

<%= form_for(@category, :html => {role: "form"}) do |f| %>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :name %> 
        </div>
        <div class="col-sm-10">
            <%= f.text_field :name, class: "input form-control", placeholder: "Category name", autofocus: true %>
        </div>
    </div>
    <br><br>
    <div class="form-group">
        <hr>
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary' %>
        </div>
    </div>
<% end %>  

app/views/layouts/_footer.html.erb
<div clas="container">
    <footer class="footer">
        <small>
            Copyright &copy Alpha-Blog 2017
        </small>
        <nav>
            <ul>
                <li><%= link_to "About", about_path %></li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>' role="alert">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <p>
    <%= msg %>
    </p>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha-Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path, :class => 'button-left' %></li>
        <%if logged_in? then %>
          <li><%= link_to "Users", users_path, :class => 'button' %></li>
          <li class="dropdown">
            <a href="#" class="button-right" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All categories", categories_path, :class => 'link' %></li>
              <li role="separator" class="divider"></li>
              <% Category.all.each do |category| %>
                <li><%= link_to category.name, category_path(category), :class => 'link' %></li>
              <% end %>
              <% if logged_in? and current_user.admin? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Create new category", new_category_path, :class => 'link' %></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "One more separated link", new_article_path, :class => 'link' %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Users ", users_path, :class => 'button-right' %></li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%if logged_in? then %>
          <li><%= link_to "Logout", logout_path, method: :delete, :class => 'button-left' %></li>
          <li class="dropdown">
            <a href="#" class="button-right" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit profile", edit_user_path(current_user), :class => 'link' %></li>
              <li><%= link_to "Wiew profile", user_path(current_user), :class => 'link' %></li>
              <li><%= link_to "Something else here", new_article_path, :class => 'link' %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Separated link", new_article_path, :class => 'link' %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path, :class => 'button-left' %></li>
          <li><%= link_to "Signup", signup_path, :class => 'button-right' %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <hr>
  <p>debug data:</p>
  <%= debug(params) if Rails.env.development? %>
  <%= render "layouts/footer" %>

</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
    <head>
        <style>
        .dropbtn {
            background-color: #4CAF50;
            color: white;
            padding: 16px;
            font-size: 16px;
            border: none;
            cursor: pointer;
        }
        
        .dropbtn:hover, .dropbtn:focus {
            background-color: #3e8e41;
        }
        
        #searchInput {
            border-box: box-sizing;
            font-size: 16px;
            padding: 14px 40px 12px 25px;
            border: none;
        }
        
        .dropdown {
            float: right;
            position: relative;
            display: inline-block;
        }
        
        .dropdown-content {
            right: 0;
            display: none;
            position: fixed;
            background-color: #f6f6f6;
            min-width: 230px;
            width: 260px;
            overflow: auto;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }
        
        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }
            
        .dropdown a:hover {background-color: #ddd}
            
            .show {display:block;}
            
            .header {
            	background-color: #e2e2e2;
                cursor: default;
            }
        
            .navbar {
                position: fixed;
                top: 0;
                width: 100%;
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
                background-color: #333333;
            }
            
            li {
                float: left;
            }
            
            li a {
                display: block;
                color: white;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }
            
            li a:hover:not(.active) {
                background-color: #8c8c8c;
            }
            
            .active {
                background-color: #2180de;
            }
            
            #indent {
                margin: 0px 0px 0px 30px;
            }
            
            #extraindent {
                margin: 0px 0px 0px 80px;
            }
        </style>
        <script>
            /* When the user clicks on the button,
            toggle between hiding and showing the dropdown content */
            function searchFunction() {
                document.getElementById("searchlist").classList.toggle("show");
            }
            
            function filterFunction() {
                var input, filter, ul, li, a, i;
                input = document.getElementById("searchInput");
                filter = input.value.toUpperCase();
                div = document.getElementById("searchlist");
                a = div.getElementsByTagName("a");
                for (i = 0; i < a.length; i++) {
                    if (a[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
                        a[i].style.display = "";
                    } else {
                        a[i].style.display = "none";
                    }
                }
            }
        </script>
    </head>
    <body>
        <ul class="navbar">
          <li><a href="home">Home</a></li>
          <li><a href="more">More</a></li>
          <li style="float:right"><a href="news">News</a></li>
          <li style="float:right"><a href="contact">Contact</a></li>
          <li style="float:right"><a class="active" href="about">About</a></li>
          <li style="float:right"><a onclick="searchFunction()" href="#search">Search</a></li>
        </ul>
        <br>
        <br>
        <div class="dropdown">
            <div id="searchlist" class="dropdown-content">
                <input type="text" placeholder="Search.." id="searchInput" onkeyup="filterFunction()">
                <a href="about">About</a>
                <a href="contact">Contact</a>
                <a href="home">Home</a>
                <a href="news">News</a>
                <a href="more" class="header">More</a>
                <a href="games">Games</a>
                <a href="tutorials">Tutorials</a>
            </div>
        </div>
        <div style="background-color:#404040;color:white;padding:20px;">
            <img alt="HMI Studios logo" id="indent" src='https://hmigames.files.wordpress.com/2016/04/hmi.png?w=100'>
            <br>
            <h2 id="indent">HMI STUDIOS</h2>
            <p id="indent"><em>The Official HMI Website.</em></p>
            <br>
        </div>
        <p><a href="about">about></a></p>
    </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1>ALPHA-BLOG</h1>
    <%= link_to "Sign up", "signup", class: "btn btn-primary btn-lg btn-xlarge" %>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <h2>The following errors prevented the user from getting created</h2>
    
    <div class="alert alert-danger" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <p><%= @user.errors.full_messages.length %> errors prohibited this user from being saved</p>
        <% @user.errors.full_messages.each do |msg| %>
            <p>&emsp;
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <%= msg %>
            </p>
        <% end %>
    </div>
<% end %>

<div class="row">
    <div class="col-xs-12">
      <%= form_for(@user, :html => {role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :username %> 
                </div>
                <div class="col-sm-10">
                    <%= f.text_field :username, class: "input form-control", placeholder: "Enter username", autofocus: true %>   
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :email %>
                </div>
                <div class="col-sm-10">
                    <%= f.email_field :email, class: "input form-control", placeholder: "Enter email", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :password %> 
                </div>
                <div class="col-sm-10">
                    <%= f.password_field :password, class: "input form-control", placeholder: "Enter password", autofocus: true %>   
                    <div class="form-group">
                        <hr>
                        <div class="col-sm-0">
                            <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary") %>
                            <%= link_to "Back to users listing", users_path, style: 'float: right' %>
                            <% if @user.new_record? then %>
                                <hr>
                                Already have an account?
                                &nbsp;&nbsp;
                                <%= link_to "Login", login_path, class: 'btn btn-primary' %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>  
    </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Alpha Bloggers</h1>

<%= link_to "Signup", signup_path, class: "btn btn-xs btn-primary" %>
<br>
<br>

<script>
$(document).ready(function() {
  $("#search").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#table tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

<input class="form-control" id="search" type="text" placeholder="Search..">
  
<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody id="table">
    <% @users.each do |user| %>
        <tr>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <% if logged_in? and (current_user == user or current_user.admin?) then %>
                <td><%= link_to "Edit", edit_user_path(user), class: "btn btn-xs btn-primary" %></td>
                <td><%= link_to "Delete", user_path(user), method: :delete, 
                    data: {confirm: "Are you sure you want to delete this user?"}, 
                    class: "btn btn-xs btn-danger" %></td>
            <% else %>
                <td><button class="btn btn-xs btn-primary" disabled>Edit</button></td>
                <td><button class="btn btn-xs btn-danger" disabled>Delete</button></td>
            <% end %>
            <td><%= link_to "View", user_path(user), class: "btn btn-xs btn-success" %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<h1 align="center">Signup for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page </h1>

<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
        <%= gravatar_for @user, size: 150 %>
    </div>
</div>

<h4 align="center"><%= @user.username %>'s articles</h4>

<%= render 'articles/article', obj: @user.articles %>